### ISSUE TITLE
Debug support when use lsp-dart, dart-mode with hover.el ?

### ISSUE THREAD

**Issue by zw963** [ericdallo/hover.el#10]
I can start `hover run` correctly on my laptop with arch linux.

but, no see any document about how to debug on it, any idea?

thank you.

**Comment by ericdallo** [comment]
@zw963 AFAIK there is no debug support on hover or I never heard of such feature as `hover run` only run `flutter run` under the hood, and to debug a app is not that simple

**Comment by zw963** [comment]
just curious，is there any different when run from hover on Linux than run `flatter run  -d linux ` directly?

**Comment by ericdallo** [comment]
yes, hover emulates the widgets with OPENGL, it's way lighter than running a emulator, I use hover all the time, I use emulators only when hover can't solve my problems

**Comment by zw963** [comment]
Yes, genymotion consume my 3 GB memory (default value) unexpectly (never consider it will use so much), make my system lag, i switch to use hover for now too.

thank you for explain.
