### ISSUE TITLE
Hover not work if current hover-mode was start on another frame

### ISSUE THREAD

**Issue by zw963** [ericdallo/hover.el#11]
Both `hover-run-or-hot-reload` and `hover-hot-reload-on-save` option all not works if current hover-mode buffer was switch back to hidden this buffer.

```cl
Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
  hover--run-command-on-hover-buffer("r")
  hover--hot-reload()
  run-hooks(after-save-hook)
  basic-save-buffer(nil)
  #<subr save-buffer>(1)
  ad-Advice-save-buffer(#<subr save-buffer> 1)
  apply(ad-Advice-save-buffer #<subr save-buffer> 1)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  #<subr command-execute>(save-buffer nil nil nil)
  ad-Advice-command-execute(#<subr command-execute> save-buffer)
  apply(ad-Advice-command-execute #<subr command-execute> save-buffer)
  command-execute(save-buffer)
```

**Comment by zw963** [comment]
I consider another issue is related to this one.

whenever i save my buffer (when set hover-hot-reload-on-save t), or run `hover-run-or-hot-reload`, hover-mode buffer window always try to pop up aggressively.

 if current only one buffer window is opened(except treemacs window), it work well, because
hover will try to enable a new buffer window and show it.

but, if current we have two buffer window, like this.

![image](https://user-images.githubusercontent.com/549126/149324130-cb965ad8-14e5-4e3b-a73f-53f91f98a835.png)

will always raise this error, and seem like hot reload not take effect too because error.

**Comment by ericdallo** [comment]
> Both hover-run-or-hot-reload and hover-hot-reload-on-save option all not works if current hover-mode buffer was switch back to hidden this buffer.

Not sure I understood your issue, hot did you reproduce that?

the popup window should be configured in your emacs, as hover only uses the `compilation-start` function to start a process in a buffer.

**Comment by zw963** [comment]
> Not sure I understood your issue, hot did you reproduce that?

Okay, wait several minutes, i will add a reproducable config later.




> the popup window should be configured in your emacs, as hover only uses the `compilation-start` function to start a process in a buffer.

How you configure popup window? popwin or shackle ? or any others?

**Comment by zw963** [comment]
Okay i can reproduce now:

1. open dart-mode, with hover config.
2.  run `hover-run-or-hot-reload`, to start hover, a compile buffer window is opened.

for now all work as expected, following i have two usage issue:

### first issue
3.  when i run `hover-run-or-hot-reload` again after edit, it always raise a compile (hover-mode) buffer, that quite bothering.
     i guess you answer this question in previous comment reply (use popup window), can i know how to do that?
     
### second issue
i consider this issue caused by previous issue.

i need open multi frame for some case, e.g. one frame open ruby file, another frame open dart with hover.

following is repoduce:

1. open a new frame use `make-frame`.

2. run `hover-run-or-hot-reload` on new frame, git above issue.

----------------

I consider a fix is, if we can not always make compile buffer became a foreground buffer and want to show it aggressively, this maybe not a issue.

**Comment by ericdallo** [comment]
thanks, I'll try to reproduce this on the weekend

> the popup window should be configured in your emacs, as hover only uses the compilation-start function to start a process in a buffer.

I use doom's `set-popup-rule!`, not sure what it does under the hood

**Comment by zw963** [comment]
> I use doom's `set-popup-rule!`, not sure what it does under the hood

Hi, i reference your's config, no see any related config?

```
(set-popup-rule! "\\*LSP Dart tests\\*" :height 0.3)
(set-popup-rule! "\\*dap-ui-locals\\*" :side 'right :width 0.3)
(set-popup-rule! "\\*dap-ui-sessions\\*" :side 'right :width 0.3)
(set-popup-rule! "\\*midje-test-report\\*" :side 'right :width 0.5)
(set-popup-rule! "*cider-test-report*" :side 'right :width 0.4)
(set-popup-rule! "^\\*cider-repl" :side 'bottom :quit nil)
```

Which one?

**Comment by ericdallo** [comment]
I think this one is configured on doom's side :/ not sure about how to solve that, search for `emacs compilation-start buffer` and how to manage it properly

**Comment by zw963** [comment]
> I think this one is configured on doom's side :/ not sure about how to solve that, search for `emacs compilation-start buffer` and how to manage it properly

Thank you for you help, I finally resolve the first one popup issue with [popper](https://github.com/karthink/popper) package.

it work well for now.

**Comment by zw963** [comment]
BTW: maybe you want to try popper, key feature is:

1. one key toggle the last (hidden) popped windows.
2. one key to show all hidden popped window one by one cyclely.
3.  can hide special buffer.

for resolve my current issue 1, following is my config:

```cl
(setq popper-reference-buffers
      '("\\*Messages\\*"
        "Output\\*$"
        "\\*Async Shell Command\\*"
        "Scratch.txt"
        vterm-mode
        (special-mode . hide)
        (hover-mode . hide)
        (compilation-mode . hide)
        help-mode
        ))
```

when hover run start, i can saw some info in my minibuffer, like this:

![image](https://user-images.githubusercontent.com/549126/149562810-5e648686-387b-4c89-baec-14ab1b5a5498.png)

**Comment by zw963** [comment]
Maybe this issue was not about hover, close for now.
