### ISSUE TITLE
emulator replacement

### ISSUE THREAD

**Issue by mictadlo** [ericdallo/hover.el#17]
Hi,
Android does not provide emulators for [ARM64](https://github.com/flutter/flutter/issues/147337) Is this project a replacement for Android's emulators?

Best wishes,

Michal

**Comment by ericdallo** [comment]
sorry fo the delay, but yes @mictadlo, hover could be used for that, although this project is just a emacs layer to use hover under the hood : https://github.com/go-flutter-desktop/hover
