### ISSUE TITLE
Hover problem when running flutter app

### ISSUE THREAD

**Issue by Qkessler** [ericdallo/hover.el#4]
Following the configuration example and variables, I'm trying to configure hover to work with my flutter project. I run into the problem that hover is not recognizing the path from which I'm running the command "hover-run-or-hot-reload".

The error is the following:
```
hover: Error: No pubspec.yaml file found: open pubspec.yaml: no such file or directory
hover: This command should be run from the root of your Flutter project.

Process Hover exited abnormally with code 1

```
The error is triggered running "hover-run-or-hot-reload" from my main.dart file.

My init.el file regarding lsp-dart and hover.el:

```
(use-package lsp-dart 
  :ensure t
  :hook (dart-mode . lsp-deferred)
  :custom (lsp-dart-sdk-dir "<HOME>/snap/flutter/common/flutter/bin/cache/dart-sdk")
  (lsp-dart-flutter-sdk-dir "<HOME>/snap/flutter/common/flutter")
  (dart-format-on-save t))

(use-package hover
  :ensure t
  :after dart-mode
  :custom (hover-command-path "<HOME>/go/bin/hover")
  (hover-hot-reload-on-save t)
  (hover-flutter-sdk-path "<HOME>/snap/flutter/common/flutter")
  :bind (:map dart-mode-map ("C-M-z" . hover-run-or-hot-reload)))
```

I would love to be able to use hover, as it is the best alternative to emulators. I appreciate a lot the work you are doing, keep it up!

**Comment by ericdallo** [comment]
Hum, I'll take a look, thanks for the report!

**Comment by Qkessler** [comment]
Thank you!

**Comment by ericdallo** [comment]
@Qkessler, do you have a sample project? I tested with my [flutter_sample](https://github.com/ericdallo/flutter-sample) repo and it worked.

**Comment by ericdallo** [comment]
@Qkessler I also released a new version `1.2.1` with some refactors that may fix your issue

**Comment by Qkessler** [comment]
Hi @ericdallo ! The sample project was the default created by flutter create <name>. I will test more today, try the new version and keep you posted! Thanks!

**Comment by Qkessler** [comment]
Okey, I tested your flutter_sample project and the error is the following:

```
hover: listing available plugins:
hover: Run `flutter build bundle` (or equivalent) first
hover: no pubspec.lock file found

Process Hover exited abnormally with code 1

```
I'm guessing I'm having conflicts on configuration. When trying to exit emacs, hover launches a message on *Messages*:

`
run-hooks: Symbol’s function definition is void: hover--hot-reload
`
which forces me to kill the process with "sudo kill". Will keep testing.

**Comment by ericdallo** [comment]
Did you try running hover manually via terminal on the project folder? does that work?

**Comment by Qkessler** [comment]
Yes, it does work. I'm guessing that was the problem. Running the hover on the terminal, it said that hover might need an upgrade. I installed it and now hover.el works great! Thank you for your help Eric!

**Comment by ericdallo** [comment]
Nice :)

**Comment by ericdallo** [comment]
BTW, there's `hover-kill` command which kills hover buffer
