### ISSUE TITLE
Configuration of hover window

### ISSUE THREAD

**Issue by Qkessler** [ericdallo/hover.el#5]
Hey, I hope everything is going fine!
I was trying out hover again this afternoon and was wondering about the possibility of configuring the hover output window. I was guessing that the hover window gets initialized to the space that it has available, but I find that my hover window isn't really scaled correctly.
I checked the readme again as I remembered that there was an example gif on it and I saw that the example shows a hover window that has been configured (or scaled automatically) to look like a phone screen!
I would love the information to be contained in the readme or documentation! 
Have a great day!
Enrique.

**Comment by ericdallo** [comment]
Hello, `hover.el` just start a `compilation` process that creates a buffer, it's not its responsibility to handle the window or buffer position, this should be done by your emacs config or framework (in my case doom-emacs).
Also above you can see only the buffer created from `hover.el`
![image](https://user-images.githubusercontent.com/7820865/111686134-75f3e980-8807-11eb-955f-c02643d158d9.png)

The phone screen on right is the emulator itself, nothing related with emacs, I just scaled my emacs window to make the gif show both emacs and the emulator screen 😅

**Comment by Qkessler** [comment]
Hi Eric! I know the hover binary is called. I was just wondering because I'm having trouble using the hover window on one of my monitors, which seemed weird enough to ask. 
Here, the first image shows the hover window working on my first monitor, working perfectly.
![first_screen](https://user-images.githubusercontent.com/47970396/111687172-41ddf000-882a-11eb-80c1-be14e4bce084.png)

On the second image, I just move the same window to the second monitor (which has a resolution 1920:1080).
![second_screen](https://user-images.githubusercontent.com/47970396/111687285-6639cc80-882a-11eb-9984-dc2e63058105.png)

Should I ask on the hover project? Also, would you mind pasting some of the configuration that allows you to set the hover.el buffer closer to the minibuffer? Mine occupies most of the screen!
Thanks again Eric,
Enrique.

**Comment by ericdallo** [comment]
Yes, sorry but that's definitely a [hover issue](https://github.com/go-flutter-desktop/go-flutter) since it's not updating the running app with the new screen pixel ratio.

My config is specific for doom-emacs, it does that as default for new buffers, you can find it [here](https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/dart/config.el#L54-L66), but you will need to debug further to understand how it handle windows though.

**Comment by Qkessler** [comment]
Closing this as there is nothing more to be done. Thanks Eric, you are always so quick responding! Keep it up! :smile:
