### ISSUE TITLE
Silence Hover autocompile pop-up buffer?

### ISSUE THREAD

**Issue by tzbob** [ericdallo/hover.el#7]
I'm a bit of an Emacs noobie, but is there a way to stop the *Hover* buffer from popping up on every reload? Thanks!

**Comment by ericdallo** [comment]
hey, what do you mean by popping up? I think this depends on how your emacs is managing the hover buffer, if you are using doom-emacs or spaceemacs for example they have options to change how that behaves, otherwise, could you show a gif with the issue?

**Comment by tzbob** [comment]
Oops I should've made this a bit more clear. What I meant is that even though I close a window for the buffer it pops up every time a hot reload is performed, being able to keep it closed and peeking at it when I want would be my preferred behavior.

**Comment by ericdallo** [comment]
The behaviour or your emacs is to show changed buffers, not sure how to fix it for you but what you can do that certainly will avoid that is to disable the auto reload with `(setq hover-hot-reload-on-save nil)`, and when you want to hot reload you just enter the buffer and press `r`

**Comment by tzbob** [comment]
Alright that explains it perfectly, thanks! I love the fast reload on save so I'll just make a tiny frame with the hover buffer and keep it there.
